services:
  app:
    build:
      context: .
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    container_name: clone-tabnews-node-18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
